#!/bin/sh
root="`dirname $0`"
assertions=""
if [ "$1" = "-ea" ]
then
    echo Turning on assertions.
    assertions="-ea"
    shift
fi
if [ -f "$root"/bibweb.jar ]
then
    echo java $assertions -cp "$root"/bibweb.jar bibweb.Main $*
    java $assertions -cp "$root"/bibweb.jar bibweb.Main $*
elif [ -d "$root"/bin -a -d "$root/easyIO/bin" ]
then
    java $assertions -cp "$root"/bin:"$root"/easyIO/bin:"$root"/jbibtex/target/classes bibweb.Main $*
else
    echo "Don't know where to find bibweb.jar"
    exit 1
fi
