bibfile: example.bib

pubs:
.abadi99:
..authors: Mart&iacute;n Abadi and Andrew D. Gordon
..topic: security languages
..
.dummy1:
..pubtype: inproceedings
..pubtitle: A fake paper
..authors: John Doe and Jane Doe
..booktitle: A fake conference
..year: 2015
..month: June
..
.

% comment

generate:
.output: example.html
.section:
..intro: <h2>All publications</h2>
..
.section:
..intro: <h2>Publications by Andrew Gordon</h2>
..select:
...author: Andrew D. Gordon
...
..
.
